INSERT INTO product (name, amount, price,discount_percent) VALUES ('APhone', 12,3, 44.23);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('BPhone', 14,2, 74.34);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('CPhone', 16,4, 94.06);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('DPhone', 13,6, 74.59);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('EPhone', 11,0, 24.98);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('FPhone', 18,0, 44.95);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('GPhone', 16,2, 74.96);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('HPhone', 19,8, 84.87);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('IPhone', 13,6, 24.78);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('JPhone', 15,4, 44.66);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('KPhone', 14,2, 14.52);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('LPhone', 18,2, 64.49);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('MPhone', 12,0, 74.39);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('NPhone', 11,0, 34.16);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('OPhone', 19,4, 34.18);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('PPhone', 15,30,34.16);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('QPhone', 13,3, 34.76);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('RPhone', 17,2, 34.54);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('SPhone', 19,6, 34.93);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('TPhone', 20,5, 34.72);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('UPhone',  9,50,34.59);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('VPhone',  5,30,34.55);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('WPhone', 10,5, 34.76);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('XPhone', 11,8, 34.86);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('YPhone', 19,8, 34.56);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('ZPhone', 18,9, 34.96);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('APhone', 18,7, 34.36);
INSERT INTO product (name, amount, price,discount_percent) VALUES ('APhone', 16,5, 34.46);

INSERT INTO public.discount_card (discount) VALUES (50);
INSERT INTO public.discount_card (discount) VALUES (3);
INSERT INTO public.discount_card (discount) VALUES (3);
INSERT INTO public.discount_card (discount) VALUES (5);
INSERT INTO public.discount_card (discount) VALUES (5);
INSERT INTO public.discount_card (discount) VALUES (10);
INSERT INTO public.discount_card (discount) VALUES (15);
INSERT INTO public.discount_card (discount) VALUES (8);

INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 30.00, 34, 4);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 40.00, 34, 13);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 50.00, 24, 14);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 60.00, 54, 24);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 70.00, 64, 12);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 80.00, 24, 10);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 90.00, 84, 8);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 50.00, 34, 9);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 30.00, 64, 15);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 40.00, 94, 12);
INSERT INTO public.check (total_price_with_discount, total_price, discount_amount, total_percent) VALUES (10.00, 100.00,14, 11);

INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (10.00, 1,1, 30.00, 34.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (20.00, 2,2, 40.00, 44.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (30.00, 3,3, 50.00, 64.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (40.00, 4,4, 60.00, 74.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (50.00, 5,5, 70.00, 84.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (60.00, 6,6, 80.00, 94.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (70.00, 7,7, 90.00, 54.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (80.00, 8,8, 70.00, 64.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (90.00, 9,9, 80.00, 74.00, 7);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (10.00,10,10, 20.00, 84.00, 8);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (80.00,11,11, 30.00, 94.00, 9);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (70.00, 1,12, 50.00, 54.00, 3);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (60.00, 2,13, 60.00, 64.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (50.00, 3,14, 70.00, 74.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (40.00, 4,15, 80.00, 84.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (30.00, 5,16, 90.00, 94.00, 7);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (20.00, 6,17, 30.00, 94.00, 8);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (30.00, 7,18, 10.00, 84.00, 9);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (40.00, 8,2, 30.00, 74.00, 0);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (50.00, 9,3, 20.00, 64.00, 3);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (60.00,10,4, 30.00, 74.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (70.00,11,5, 90.00, 84.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (80.00, 1,6, 80.00, 94.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (10.00, 2,7, 70.00, 84.00, 3);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (20.00, 3,8, 60.00, 74.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (30.00, 4,9, 50.00, 64.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (40.00, 5,10, 60.00, 74.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (50.00, 6,10, 70.00, 84.00, 7);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (60.00, 7,11, 80.00, 94.00, 8);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (70.00, 8,21, 90.00, 84.00, 9);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (80.00, 9,22, 80.00, 74.00, 8);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (90.00,10,22, 70.00, 64.00,7);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (10.00,11,23, 60.00, 74.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (20.00, 1,24, 50.00, 84.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (30.00, 2,25, 60.00, 94.00, 4);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (40.00, 3,25, 70.00, 84.00, 5);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (50.00, 4,24, 80.00, 74.00, 6);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (60.00, 5,26, 90.00, 84.00, 7);
INSERT INTO public.product_information (price_with_discount, check_id,product_id, total_price, total_price_with_discount,discount_percent) VALUES (70.00, 6,27, 80.00, 94.00, 8);